/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 10.1.10-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `tb_menu` (
	`menu_id` int (11),
	`parent_id` int (11),
	`module` varchar (150),
	`url` varchar (300),
	`menu_name` varchar (300),
	`menu_type` char (30),
	`role_id` varchar (300),
	`deep` smallint (2),
	`ordering` int (6),
	`position` char (21),
	`menu_icons` varchar (90),
	`active` char (3),
	`access_data` text ,
	`allow_guest` char (3),
	`menu_lang` text ,
	`entry_by` varchar (30)
); 
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('55','0','','','Master Tanaman','internal','0','0','3','sidebar','fa fa-database','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('56','55','mjenistanah','','Jenis Tanah','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('57','55','mkategori','','Kategori Petak','internal','0','0','3','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('58','55','mkondisiareal','','Kondisi Areal','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('59','0','','','Tebang Angkut','internal','0','0','4','sidebar','fa fa-truck','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('60','0','','','Master SDM','internal','0','0','2','sidebar','fa fa-group','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('61','60','mjabatan','','Data Jabatan','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('62','60','mkaryawan','','Data Karyawan','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('63','0','','','Tanaman','internal','0','0','5','sidebar','fa fa-cogs','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('64','63','tkuotaspta','','Kuota SPTA','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('65','63','tcetakulang','','Cetak Ulang & Retur SPTA','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('66','0','tmejatebu','','Meja Tebu','internal','0','0','7','sidebar','fa fa-barcode','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('67','0','tanalisarendemen','','Analisa ARI','internal','0','0','8','sidebar','fa fa-building-o','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('68','0','tsbh','','Sistem Bagi Hasil','internal','0','0','9','sidebar','fa fa-credit-card','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"6\":\"0\",\"7\":\"1\",\"8\":\"0\",\"9\":\"0\",\"10\":\"1\",\"11\":\"1\",\"12\":\"1\",\"13\":\"1\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('39','0','','','Dashboard','internal','0','0','1','sidebar','fa fa-dashboard','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\"}','0',NULL,'1');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('71','55','mstatusblok','','Status Blok','internal','0','0','5','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('72','55','mpetanipetak','','Data Petani','internal','0','0','7','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('69','0','','','Monitoring SPTA','internal','0','0','10','sidebar','fa fa-desktop','0','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','1',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('70','55','mvarietas','','Varietas','internal','0','0','4','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('73','55','mmasterfield','','Master Field','internal','0','0','6','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('74','0','','','Pengolahan','internal','0','0','11','sidebar','fa fa-book','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\"}','1',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('75','74','tlapharpeng','','Harian Giling','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"6\":\"0\",\"7\":\"1\",\"8\":\"0\",\"9\":\"0\",\"10\":\"1\",\"11\":\"0\",\"12\":\"0\",\"13\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('76','74','','','telegram Giling','internal','0','0','2','sidebar','','0','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('77','74','','','Evaluasi Giling','internal','0','0','3','sidebar','','0','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('78','74','','','Hasil Pasti','internal','0','0','4','sidebar','','0','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('79','60','mafdeling','','Data Afdeling','internal','0','0','3','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('80','59','mupahtebang','','Master Upah & Potongan','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('81','0','tselektor','','Selektor','internal','0','0','6','sidebar','fa fa-download','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('82','0','','','Master Data Khusus','internal','0','0','2','sidebar','fa fa-database','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('83','82','mmejatebu','','Meja Tebu','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('84','82','mlori','','Data Lori','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('85','82','mtimbangan','','Data Timbangan','internal','0','0','3','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('86','59','mvendor','','Vendor Angkutan','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('87','59','mjarak','','Master Jarak','internal','0','0','5','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('88','59','tbiayaangkutan','','Proses Upah Angkutan','internal','0','0','7','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('89','59','tupahtebang','','Proses Upah Tebang','internal','0','0','6','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('90','63','tevaluasitebang','','Evaluasi Tebang','internal','0','0','3','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('91','0','','','Laporan','internal','0','0','12','sidebar','fa fa-print','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"1\",\"8\":\"1\"}','1',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('92','91','laporantimbangan','','Laporan Timbangan','internal','0','0','1','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"1\",\"8\":\"1\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('93','91','laporanari','','Laporan A.R.I','internal','0','0','3','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"6\":\"1\",\"7\":\"1\",\"8\":\"1\",\"9\":\"1\",\"10\":\"1\",\"11\":\"1\",\"12\":\"1\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('94','91','laporanmejatebu','','Laporan Meja Tebu','internal','0','0','2','sidebar','','1','{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"1\",\"8\":\"1\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('95','82','mkualitastebu','','Master Rafaksi','internal','0','0',NULL,'sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"9\":\"0\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('96','0','tspt','','Surat Perintah Tebang','internal','0','0','2','sidebar','fa fa-file','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"9\":\"0\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\"}','0',NULL,'22');
insert into `tb_menu` (`menu_id`, `parent_id`, `module`, `url`, `menu_name`, `menu_type`, `role_id`, `deep`, `ordering`, `position`, `menu_icons`, `active`, `access_data`, `allow_guest`, `menu_lang`, `entry_by`) values('97','74','lapproduksi','','Lap. Produksi','internal','0','0','5','sidebar','','1','{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"6\":\"0\",\"7\":\"1\",\"8\":\"0\",\"9\":\"0\",\"10\":\"1\",\"11\":\"0\",\"12\":\"0\",\"13\":\"0\"}','0',NULL,'22');
